import "./ui/globals.css";

// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

import type { Metadata } from "next";
import { promt } from "./ui/fonts";
import { auth } from "@/auth";
import { ApolloWrapper } from "./ui/context/apollo-provider";
import SessionProvider from "./ui/context/session-provider";
import clsx from "clsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" data-theme="lemonade">
      <body className={clsx(promt.className, "")}>
        <SessionProvider session={session}>
          <ApolloWrapper>{children}</ApolloWrapper>
        </SessionProvider>
        <div id="modal-container"></div>
        <div id="loading-backdrop-container"></div>
        <div id="datepicker-container"></div>
      </body>
    </html>
  );
}
